name: CI

env:
    DISCOGS_TOKEN: ${{ secrets.DISCOGS_TOKEN }}
    STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
    STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
    STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        name: Lint
        runs-on: ${{ matrix.os-version }}

        strategy:
            matrix:
                node-version: [24.x]
                os-version: [ubuntu-latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4.1.0
              with:
                  version: 8

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm i

            - name: Check for lint and formatting errors
              run: pnpm lint

    build:
        name: Build
        runs-on: ${{ matrix.os-version }}
        needs: lint

        strategy:
            matrix:
                node-version: [24.x]
                os-version: [ubuntu-latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4.1.0
              with:
                  version: 8

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm i

            - name: Build site
              run: pnpm build
